version: 2.1
jobs:
  test:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: prod
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.clean --all, clean # dialyzer plts survive this
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: MIX_ENV=test mix coveralls.circle
      - run: mix credo
      - run: mix format --check-formatted
      - run: mix dialyzer --plt
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - _build
      - save_cache:
          key: v1-{{ epoch }}
          paths:
            - _build
      - run: MIX_ENV=prod mix dialyzer --halt-exit-status
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
